name: Build
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
defaults:
  run:
    working-directory: ./packages/ui
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    name: 📦️ Build Node-${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v6
      - name: 🔧 Install JS dependencies
        uses: siguici/setup-js@v1
        with:
          runtime: bun
          version: ${{ matrix.bun-version }}
      - name: 🔨 Install JavaScript dependencies
        run: bun install
      - name: ✅ Fix code style and build for production
        run: bun run build
      - name: 📂 Upload Deno distribution files
        uses: actions/upload-artifact@v6
        with:
          name: deno_dist
          path: packages/ui/jsr
          overwrite: true
