name: CI

permissions:
  contents: read

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.5]
        dependency: [prefer-stable]
        experimental: [false]
    name: 👷 CI PHP-${{ matrix.php }} ${{ matrix.dependency }} with Node-${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 📂 Cache dependencies
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-

      - name: ⚡️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, gd, intl, mbstring, openssl, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2, php-cs-fixer, phpunit, vimeo/psalm
          coverage: pcov

      - name: 📦 Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --no-ansi --no-cache --no-interaction --no-scripts --no-progress --prefer-dist

      - name: 🎉 Install JS dependencies
        uses: siguici/setup-js@v1

      - name: ✅ Fix code style and build for production
        run: make build

      - name: 🧹 Check code lint
        run: make check

      - name: ⚗️ Run static analysis
        run: |
          composer analyse

      - name: 🧪 Test features
        run: make test
